PIPELINE_MODEL_NAME=mnist \
PIPELINE_MODEL_TAG=v1 \
PIPELINE_MODEL_TYPE=tensorflow \
PIPELINE_MODEL_RUNTIME=tfserving \
PIPELINE_MODEL_CHIP=cpu \
PIPELINE_INPUT_PATH= \
PIPELINE_OUTPUT_PATH= \
  python pipeline_train.py