PIPELINE_MODEL_NAME=inception \
PIPELINE_MODEL_TAG=cpu \
PIPELINE_MODEL_TYPE=tensorflow \
PIPELINE_MODEL_RUNTIME=tfserving \
PIPELINE_MODEL_CHIP=cpu \
PIPELINE_INPUT_PATH= \
PIPELINE_OUTPUT_PATH= \
  python pipeline_predict.py