PIPELINE_MODEL_NAME={{ PIPELINE_MODEL_NAME }} \
PIPELINE_MODEL_TAG={{ PIPELINE_MODEL_TAG }} \
PIPELINE_MODEL_TYPE={{ PIPELINE_MODEL_TYPE }} \
PIPELINE_MODEL_RUNTIME={{ PIPELINE_MODEL_RUNTIME }} \
PIPELINE_MODEL_CHIP={{ PIPELINE_MODEL_CHIP }} \
PIPELINE_INPUT_PATH={{ PIPELINE_INPUT_PATH }} \
PIPELINE_OUTPUT_PATH={{ PIPELINE_OUTPUT_PATH }} \
  python pipeline_predict.py
