PIPELINE_RESOURCE_NAME=zscore \
PIPELINE_RESOURCE_TAG=cpu \
PIPELINE_RESOURCE_SUBTYPE=python \
PIPELINE_RESOURCE_RUNTIME=python \
PIPELINE_RESOURCE_CHIP=cpu \
PIPELINE_INPUT_PATH=../input \
PIPELINE_OUTPUT_PATH=. \
  python pipeline_train.py
