channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.6
  # use numpy 1.14.5 instead of latest
  # numpy 1.15 raises RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  # see: https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility
  - numpy==1.14.5
  - pandas>=0.23.4
  - scikit-learn>=0.19.2
  - xgboost==0.72.1
  - pip:
    - pipeline-runtime==1.0.11
